### ISSUE TITLE
Profiling .csv's rewriting instead of appending

### ISSUE THREAD

**Issue by solejar** [radical-cybertools/radical.entk#168]
When running a script with two patterns, the second pattern will overwrite the .csv created by the first pattern. I am currently using a workaround by adding a .csv filename attribute to the pattern constructor, but just thought I should put up a ticket, as it seems to be a fairly meaningful bug.

**Comment by vivek-bala** [comment]
Thanks Sean. This indeed is the case and should be fixed in the next release (new_arch branch does pattern based profiling but the patterns are different). 

Also, upon discussion with Giannis about your application, I think the 1 SAL pattern might better suit your application that 2 BoT patterns. Althought the pattern is called "simulation" "analysis", you can use the pattern for any kernel.

**Comment by vivek-bala** [comment]
Profiling has been changed to be compatible with analytics. NA.
