### ISSUE TITLE
State model for task manager - independent of RTS -- design discussion

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.entk#243]
To keep the interaction between EnTK and an RTS independent of the specific RTS used

**Comment by mturilli** [comment]
If we get github discussions, this should be transitioned there.

**Comment by iparask** [comment]
Does this have to do with the task states or the RTS state? I've realized that EnTK does not distinguish between the final states of an RTS. Would it make sense to map the state of the RTS to internal states?

**Comment by mturilli** [comment]
This refers to separating by design (and eventually implementation) EnTK and RTS. Originally, this was derived from the requirements to use other task execution systems, e.g., Dask and others that now have disappeared. Today, this requirement is less urgent and I would suggest to de-prioritize against the one of designing EnTK for better performance. Comments, suggestions?

**Comment by andre-merzky** [comment]
I agree with Matteo.  I mean, we probably want to make sure that adding another RTS is still possible, but it is not highest priority right now.

> I've realized that EnTK does not distinguish between the final states of an RTS. Would it make sense to map the state of the RTS to internal states?

IMHO distinguishing final states is a necessity.  If that is done via mapping into an RE state model or by having the RE state model expand the RTS/RP state model is really an implementation detail.  Mapping will be required once we add a second RTS, until then it does not matter...

**Comment by iparask** [comment]
moved in discussions
