### ISSUE TITLE
pika 1.0.0 compatibility issue

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#331]
[pika 1.0.0](https://github.com/pika/pika/releases) is released and the [changelog](https://github.com/pika/pika/blob/1.0.0/CHANGELOG.rst) says "the callback parameter that indicates completion of the method has been moved to the end of the parameter list to be consistent with other parts of Pika's API and with other libraries in general." For example, [pika.channel.basic_consume](https://pika.readthedocs.io/en/stable/modules/channel.html#pika.channel.Channel.basic_consume) is now callable with a queue parameter first e.g. ``basic_consume(callback, queue=q)``, which was used to be after callback in [0.13.1](https://pika.readthedocs.io/en/0.13.1/modules/channel.html#pika.channel.Channel.basic_consume).

**Comment by mturilli** [comment]
@lee212 , thank you for pointing this out. Would you be happy to have a look at EnTK code and see whether you can propose a PR for supporting the new call?

**Comment by lee212** [comment]
Started at `fix/issue_331` branch with a initial commit 65a78e1b681fcf00ac78d20bd24cd04163b5e291

**Comment by andre-merzky** [comment]
Our style guide is silent on this.  Always naming parameters seems like overkill to me, and would only convolute otherwise simple calls (`for in in range(stop=5):`, `i_min = min(arg1=3, arg2=4)`, `q.put(item=3)` etc.).  On long argument lists it often makes sense, specifically if the order of arguments is hard to remember (`popen`), if many arguments have the same type, or if different subsets of arguments are routinely used (even if one subset would work w/o keys).

I think I would not formalize this in the guide, as we don't have any major problems in that respect IMHO, and it is difficult to check automatically.

**Comment by vivek-bala** [comment]
Yea I agree, probably doesn't make sense to do it for every function. But I would suggest this when we are interfacing with underlying tools (pika, even utils or RP). 

I agree on your case about Popen as well. But my suggestion is more around external tools (pika, pymongo, etc.). As in this example, I don't see why Pika would change the order of the arguments and if we keep our usage positional, we run into such **unexpected** issues.

**Comment by andre-merzky** [comment]
You can't shield against all changes in underlying library, and specifically not unexpected ones. Trying to do that will result in cumbersome and inefficient code.  We should use tests to capture those cases, make sure dependencies are specified correctly, and that's about it.

**Comment by mturilli** [comment]
If nothing else this should teach a meta lesson: never, ever change an API if not strictly necessary :) Otherwise, yes, complete shielding is cumbersome but also no shielding at all is as much undesirable. In the case of this ticket, I would go with named arguments as it is not cumbersome but I would not extend this approach to every possible case. The rule that comes to mind could be something like: always try to do it as far as it is not obviously cumbersome. In other terms, let's try to minimize (instead of eliminate) the fall out from API changes.

As a side note but related to the discussion about arguments, you my find this interesting: https://www.python.org/dev/peps/pep-0570/

**Comment by lee212** [comment]
I had a different thought on this, like freezing pika version rather than using keyword arguments because this case `basic_consume` has updated with a new keyword name from `consumer_callback` to `on_message_callback`.

**Comment by andre-merzky** [comment]
@lee212 , @mturilli : Whats the state  of this?  the branch (fix/issue_331) exists since 6 months, and we carry it from release to release.  Is this fix needed?  When should it be merged?

**Comment by mturilli** [comment]
@iparask could you review `fix/issue_331`? We can then discuss what to do with this.

**Comment by iparask** [comment]
Yes.

**Comment by iparask** [comment]
Pika is frozen in the setup file to version `0.13.0`. We can keep this issue open as #480 has to do with the same subject. Having said that I deleted the `fix/issue_331` branch as it was the same with devel

**Comment by mturilli** [comment]
Does it make sense to have a look at the current version of pika and see whether upgrading has some advantages? I am worried we will end up too behind master. It is true we may eliminate pika/rbmq altogether but maybe worth a brief investigation? Thoughts?

**Comment by iparask** [comment]
> Does it make sense to have a look at the current version of pika and see whether upgrading has some advantages? 

Based on my understanding, there are no performance benefits from updating to pika 1.1.0, apart from API changes. I suggest avoiding changing the pika version until at least pika 1.2.0.

> I am worried we will end up too behind master. It is true we may eliminate pika/rbmq altogether but maybe worth a brief investigation? Thoughts?

Pika 0.13 was released on February '19 and 1.1.0 on July '19. There is a `1.2.0` milestone in pika github, but it is open from July '19, and it goes very slow. I do not think it will be updated significantly any time soon.

If you agree, I suggest we close this issue

**Comment by mturilli** [comment]
Thanks!
