### ISSUE TITLE
Reproducing the pipeline lock issue in EnTK/RepEx

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#357]
Hi @andre-merzky @mturilli 

[Here's](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_repex.py) the script.

In this script, please look at [line 425](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_repex.py#L425) where you set the "window size", i.e. how close replicas need to be to be eligible to attempt an exchange. 

If the window is smaller than `ensemble_size` , i.e. total number of replicas, several replicas terminate extremely early. I suspect this is because certain replicas are being issued a `pipeline.resume()` when there are no md tasks added to them yet. However, setting `window_size` to be equal to `ensemble_size` removes this issue completely. While this is not an issue that invalidates any science use cases, I would like to have this be a user-tunable parameter.   

_Possibly,_ either `_check_resume` [(line 246)](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_repex.py#L246) or `_find_exchange_list` [(line 214)](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_repex.py#L246) methods are screwing up: `_check_resume` may be issuing incorrect resume commands, or `_find_exchange_list` that is supposed to return 1 list (`exchange_list`) and modify another (`self._waitlist`) is doing something either wrong or out of order. However I see no evidence of this so far. This is not supposed to happen at all because of the fact that `_find_exchange_list` returns control to `_check_exchange`, which triggers `_check_resume` so there is no scope of things happening out of order. And the correct lists are being returned based on `dump.log` that the above script generates.

**Comment by andre-merzky** [comment]
It's complicated :-)

What happens is that the selection method can return a set of replicas *not* containing the replica which is currently active, ie. on which the check_exchange method operates.  So that replica is then not suspended but carries out the exchange for the other replicas.   But at the same time it stays in the waitlist (since it is not selected for exchange, it remains eligible for a later exchange and thus stays in the waitlist).

Now, assume the exchange is getting along, but meanwhile another replica MD step finishes and again we select an exchange list.  This time, our replica from above (which is not suspended but runs the echange step) is elected for exchange, but the exchange is performed by another replica (it must be another one, since our precious replica is busy elsewhere).

Now, when that second exchange finishes, it will attempt to resume all replicas which participated, including our active one from above, the one doing the first exchange - but that was never suspended,

It boils down to what the selection method is supposed to return, and as we discussed, it would be good if you would implement unit tests for just that method in isolation.  Basically, it needs to fulfill the following conditions:

  - input: old_waitlist, selection criteria, current replica
  - output: new_waitlist, exchange_list
  - conditions:
    - len(old_waitlist) == len(new_waitlist) + len(echange_list)
    - for each repllica in new_waitlist: replica not in exchange_list
    - for each replica in exchange_list: replica not in new_waitlist
    - if exchange_list: current_replica in exchange_list

Another point: it would be fantastic if you could try to plug your algorithm into the entk code and test with the code otherwise unchanged - that would help tremendously.  So I had to spend more time in reverting the changes and changing the workload back to `/bin/sleep` than with actual debugging ;-)

Also, the code in `radical.repex` contains some of the checks listed above - I will add the last one which is the one which tripped you up.

**Comment by andre-merzky** [comment]
Thinking more about this: we could in principle lift that restriction - let me know if you want me to implement that.

**Comment by SrinivasMushnoori** [comment]
Yes this explanation makes sense. Working on changing the unit test to the way you described it, and yes I should probably have a version that uses `bin/sleep` so it saves you some trouble: my apologies. 

Secondly, I do not believe that this restriction should be removed. The reason is that for multidimensional REMD you'll want the current replica to exchange ONLY in a given dimension at a given cycle, and if in its adjacency window it does not find something it'll have to wait much longer, _potentially_ killing efficiency. Particularly when it sends off other replicas to exchange in IT'S current dimension. I do not yet know what effect it will have scientifically on multidimensional REMD, but in 1D-REMD it makes no difference. Am I making sense?

**Comment by SrinivasMushnoori** [comment]
Another thing: 
```
if exchange_list: current_replica in exchange_list
```

May cause another issue. If the above condition fails and `current_replica` is not in the exchange list, no list is returned, and all replicas in that list including `current_replica` get suspended. Then there is nothing to resume any of the replicas in this perpetual state of suspension.

**Comment by SrinivasMushnoori** [comment]
This has been resolved and can be closed.
