### ISSUE TITLE
Unable to see API Reference for users- RADICAL ENTK

### ISSUE THREAD

**Issue by krb09** [radical-cybertools/radical.entk#418]
Hello, 

I am unable to see the API reference for Users in the radical.entk 1.0.0 documentation. It gives me a blank page when I click on any of the options. 
For instance: https://radicalentk.readthedocs.io/en/latest/api/app_create/task.html does not show me anything. 

Would the page be up in the near future or are there any other resources that I can be pointed to?

Thank you,

**Comment by aydinsaribudak** [comment]
Hi all,
Developer Documentation has the same issue.
Section 10.2 looks blank:
https://radicalentk.readthedocs.io/en/latest/dev_docs/dev_api.html

**Comment by mturilli** [comment]
I marked this critical because it should be addressed before our next release on Feb 4th. @lee212 could you take care of this as part of the release process of EnTK and, maybe, PR #412?

**Comment by lee212** [comment]
This should be resolved now. I managed to build docs including API sections for dev and users.
A short explanation for this problem is that documentation for API reference requires RCT package installation during the rtd build process and the API sections were missing because package installation was failed. This can happen and behave differently compared to `pip` installation as rtd uses `easy_install` with `python setup.py install` for required packages.

**Comment by andre-merzky** [comment]
Ah, thanks for explaining!  So why does EnTK need that installation while the other RCT modules don't?

**Comment by lee212** [comment]
`sphinx.ext.autodoc` is used to build API reference page by reading docstrings from source code. This requires to be able to import packages and this is why entk installation is necessary. I find that rtd for pilot is also built with package installation.

**Comment by lee212** [comment]
@krb09 , I close this now but feel free to re-open anytime if you see this persists.
