### ISSUE TITLE
EnTK’s STDOUT messages are being redirected

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#420]
Hi,
When I enable verbose messages and run a script, STDOUT messages are being redirected. Here is a screenshot as an example.
Command:
`RADICAL_VERBOSE=DEBUG RADICAL_ENTK_VERBOSE=DEBUG python get_started.py 2> verbose.log`

![EnTK_STDOUT_msgs_redirected](https://user-images.githubusercontent.com/52974147/73555942-7e7b3c00-441c-11ea-8e53-a2fa180acdf3.png)

**Comment by andre-merzky** [comment]
Hi @aydinsaribudak , 

a couple of replies:

 - please use `RADICAL_LOG_LVL` instead of `RADICAL_VERBOSE` etc
 - what you see is not log output, but reporter output.
 - the reporter output you see comes from RP, not RE
 - you can redirect logger output with `RADICAL_LOG_TGT=radical.log`
 - you can redirect reporter output with `RADICAL_REPORT_TGT=radical.rep`
 - you can do the same for individual layers with `RADICAL_ENTK_LOG_TGT / RADICAL_PILOT_LOG_TGT` etc, and similarly for the reporter.  You can also set the log levels individually.
 - finally: RP sets the reporter tgt to `stdout` - thus the above will have limited effect for the RP reporter output.  That should not happen, and I'll fix that.  The EnTK logger / reporter should behave as expected.

HtH, Andre.

**Comment by andre-merzky** [comment]
This is addressed via radical-cybertools/radical.pilot/pull/2048

**Comment by andre-merzky** [comment]
radical-cybertools/radical.pilot/pull/2048 was merged.
