### ISSUE TITLE
pytest never finishes when running locally

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.entk#436]
This is on
```sh
$ rs

  python               : 3.7.5
  pythonpath           :
  virtualenv           : /home/merzky/radical/radical.entk.devel/ve3

  radical.entk         : 1.0.1-v1.0.1-2-g92797c93@feature-early_uid
  radical.pilot        : 1.1.1
  radical.saga         : 1.1.2
  radical.utils        : 1.1.1
```

**Comment by iparask** [comment]
I think the reason is because of the following two reasons: 1) tests still run full examples and 2) the same tests use hypothesis.

Hypothesis runs a test for 100 different inputs. As a result, every test that is a full example runs for 100 times. Also In those tests timeout by hypothesis is disabled. This causes the "never finishes" you are experiencing. I am starting to think that if the tests stop running full examples, then the tests will pass regardless if they are using hypothesis or not.

**Comment by andre-merzky** [comment]
Thanks @iparask , that seems to make sense.  Do you have any insight how useful hypothesis is for the test suite?

**Comment by iparask** [comment]
I am not sure yet. It does produce different types of input and it might find corner cases. Based on its documentation that is the purpose of hypothesis. As I am getting more accustomed to it I will realize whether or not it is useful for our systems.
