### ISSUE TITLE
User-friendly Error messages

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#452]
This issue was raised by a series of user experiences of difficulty understanding a reason for any failure by looking at error messages generated by entk. One recent report is found here: https://github.com/radical-collaboration/hpc-workflows/issues/125

Failure examples to deal with:
- incorrect resources
- incorrect project name
- terminated job by scheduler

**Comment by iparask** [comment]
I think that the exception chaining resolves these issues:

1.
```
Traceback (most recent call last):
  File "/home/iparask/Git/RADICAL/radical.entk/examples/user_guide/get_started.py", line 64, in <module>
    appman.run()
  File "/home/iparask/miniconda3/envs/rct/lib/python3.9/site-packages/radical/entk/appman/appmanager.py", line 459, in run
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: Resource host 'localhost_test' unknown.
```

I checked the other two that you mention, but it depends also on the messages and exceptions we receive from RP.

**Comment by iparask** [comment]
ping @lee212, @andre-merzky

**Comment by andre-merzky** [comment]
> @andre-merzky, can we get more exception messages for these type of failures?

I think this should be translated by RE.  The error presumably comes from the RP adaptor within the RE resource manager, is thencommunicated to the app manager which forwards to the application - there is not much RP can tell about that chain of events.  From RP perspective, the specified pilot resource on the `pmgr.submit()` call is not known - but we can't say how and why that resource was specified.  We would also not help to mention the pilot description or the pmgr, since that will tell the user nothing (they are not known entities on the RE level).
