### ISSUE TITLE
Document STDOUT/ERR

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#459]
I did not find this documented explicitly in EnTK. There is some (possibly outdated) documentation in RP. It might be worth considering whether to refer to it from EnTK's documentation.

**Comment by wilkinson** [comment]
One reason that this would be very useful is because the documentation's ["Hello world" example](https://radicalentk.readthedocs.io/en/latest/user_guide/get_started.html) writes to STDOUT. Thus, in the very first program encountered, I was unable to verify that the program behaved as expected because I had trouble verifying the output.

**Comment by mturilli** [comment]
@iparask could you have a go at this? Happy to help.
