### ISSUE TITLE
EnTK Hangs

### ISSUE THREAD

**Issue by ethzan** [radical-cybertools/radical.entk#487]
When running poe.py simple example, EnTK hangs when "Setting Up RabbitMQ system."

Log files attached. Screenshot of where it hangs also attached.

![Screen Shot 2020-10-14 at 12 55 38 PM](https://user-images.githubusercontent.com/43612547/96026096-104c9d00-0e24-11eb-920e-e64b52521329.png)

[logs.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5379974/logs.tar.gz)

**Comment by ethzan** [comment]
Just following up on this, as I'm still running into this issue. Please let me know if you need additional logs. Thanks!

**Comment by iparask** [comment]
Hello @ethzan,

I would suggest to execute the get started example under `user_guide` folder. Setup the following environment variable
- `RMQ_HOSTNAME`
- `RMQ_PORT`
- `RMQ_USERNAME`
- `RMQ_PASSWORD`

for example:
```
export RMQ_HOSTNAME=<value>
```
Then find the `radical.pilot.sandbox` folder, probably it is in your home directory.

I think you are using Anaconda python. If that is true, please change lines 49-54 of the example with:
```
    res_dict = {
        'resource': 'local.localhost_anaconda',
        'walltime': 10,
        'cpus': 1
    }
```

After that please execute the example as follows:
```
RADICAL_VERBOSE=DEBUG RADICAL_ENTK_VERBOSE=DEBUG python get_started.py
```

If it does not finish in 10 minutes, please do **one** Ctrl+C and wait again. EnTK will close all the processes it started.

After that please post here the log files. There is no need for a screenshot as it does not offer us too much information to debug.

Thank you

**Comment by mturilli** [comment]
@ethzan any follow up? Can we help?

**Comment by ethzan** [comment]
@mturilli @iparask Sorry for the delay--here are the logs. I did the above and the hanging is still happening. Thanks!

[logs.tar.gz](https://github.com/radical-cybertools/radical.entk/files/5585629/logs.tar.gz)

**Comment by iparask** [comment]
Hello @ethzan, in your home folder there should be a folder named `radical.pilot.sandbox`. In there, there should be a folder named `re.session.nbp-247-66.nbp.ruw.rutgers.edu.ethanzang.018589.0006` with a `pilot.0000` in it. In there there should be a file named `pilot.0000.log.tgz`. Can you paste that as well?

If it does not exist, remove the `rp_install` folder, tar everything and paste it here.

**Comment by ethzan** [comment]
HI @iparask, thanks for your help. I do not see that folder in `radical.pilot.sandbox`. However, I do see it in the `user_guide` folder, which was my current working directory when executing. Is this part of the issue? I have pasted the corresponding zip here. Thanks.

[re.session.nbp-247-66.nbp.ruw.rutgers.edu.ethanzang.018589.0006.zip](https://github.com/radical-cybertools/radical.entk/files/5597695/re.session.nbp-247-66.nbp.ruw.rutgers.edu.ethanzang.018589.0006.zip)

**Comment by iparask** [comment]
To me this seems like a connection issue. Can you provide me with some more information about the system you are using, its capability to ssh to localhost without a password and the type of python you are using?

**Comment by ethzan** [comment]
What information about my system would you like? I'm using a MacBook Pro 2.3 GHz Dual-Core Intel Core i5 with 8GB memory. Running `ssh localhost` gives me a `ssh: connect to host localhost port 22: Connection refused.` Should I look into ways to resolve this? Python version: `Python 2.7.16 :: Anaconda, Inc.` Thanks @iparask!

**Comment by iparask** [comment]
> Running `ssh localhost` gives me a `ssh: connect to host localhost port 22: Connection refused.` Should I look into ways to resolve this? 

EnTK and its runtime system require a passwordless ssh connection between the machine you run the script and the machine things will actually be executed. As I understand it you want to run the `local.localhost` example on your Mac. Is this correct? I would say yes try and resolve this. [Here](https://radicalentk.readthedocs.io/en/stable/install.html#setup-passwordless-ssh-access-to-hpc-resources) there are instructions on how to do it. Consider your Mac as the HPC machine :) and give it a try again.

Having said that, I suggest that you use a Linux system instead of Mac. There are constant changes in MacOS and I am not sure how well our systems support it.

>Python version: `Python 2.7.16 :: Anaconda, Inc.` 

Great!

**Comment by ethzan** [comment]
@iparask Thanks! I setup passwordless ssh to localhost on my mac, but it still appears I am running into the problem. I have attached the log files here. I am looking into setting up Linux and will try that instead + update soon.

[re.session.nbp-195-177.nbp.ruw.rutgers.edu.ethanzang.018603.0004.zip](https://github.com/radical-cybertools/radical.entk/files/5654733/re.session.nbp-195-177.nbp.ruw.rutgers.edu.ethanzang.018603.0004.zip)

**Comment by ethzan** [comment]
Reran with the `RADICAL_VERBOSE=DEBUG RADICAL_ENTK_VERBOSE=DEBUG python get_started.py` for more verbose logs and attached below.

[re.session.nbp-195-177.nbp.ruw.rutgers.edu.ethanzang.018603.0005.zip](https://github.com/radical-cybertools/radical.entk/files/5654821/re.session.nbp-195-177.nbp.ruw.rutgers.edu.ethanzang.018603.0005.zip)

**Comment by iparask** [comment]
There are no debug messages in the logs you attached. I want to verify what is happening to be on the safe side.

You are executing the script from a Linux system that has a passwordless ssh connection to `localhost`. You can test that by doing `ssh localhost`. Then you are running the `get_started` example with `local.localhost` (or `local.localhost_anaconda` if you have anaconda python as your default python).

Before you run the script setup, also the `RADICAL_LOG_LVL` like this `export RADICAL_LOG_LVL=DEBUG`. After running, please verify if there is a `radical.pilot.sandbox` folder under the home directory and in there a folder named with the same name as your session. In that folder, you should see a `pilot.0000` folder and in there a set of log files (`*.log). If there are none, please let me know; otherwise, attach them here as well.

**Comment by ethzan** [comment]
Hi @iparask, as per your suggestion to setup Linux I've setup an Ubuntu virtualBox on my Mac. I am now running into a `Connection to 127.0.0.1:32769 failed: [Error 111] Connection refused` error. Do you know how to resolve this? I've also tried ports 5672 and 32777. I've confirmed that Rabbitmq is setup properly with docker.

**Comment by iparask** [comment]
What is supposed to run connect at port 32769? Is that RMQ? Everything else seems okay. Can you SSH to localhost without a password?

**Comment by ethzan** [comment]
@iparask Yes, RMQ. And yes, I set up SSH to localhost as well. Is there a way to confirm that RMQ is setup properly? I successfully ran `sudo docker run -d --name <rmq_name> -P rabbitmq:3` but just to confirm.

**Comment by ethzan** [comment]
Working now! Synced with Srinivas, setup ssh to localhost without password, and moving to Ubuntu solved it. Thanks for your help @iparask!
